### ISSUE TITLE
Support to view images

### ISSUE THREAD

**Issue by Mych** [ddurdle/Amazon-Cloud-Drive-for-KODI#10]
To start off an option to view image files as a basic slide show would be great. More elaborate slideshows with the ability to chose a music file as background music would be next.

Even better would be support for RAW files. I tend to shoot in RAW and upload to iCloud and view as various slideshows via appleTV. If this was possible via Kodi I would be able to do everything... watch videos, images, listen to music.

**Comment by ddurdle** [comment]
Playing music would not be an issue.  I allow you to filter for both music and photos in picture mode for this reason, so that you can select a music file for playback and then playback the photos.

For the RAW, would you want it to select a generated file based on the viewing resolution, or view the full RAW file in file's native resolution ?

**Comment by Mych** [comment]
Thanks for the swift reply....

Personally I would be happy with a resolution that suitable for general
viewing... we need to have a balance between download speed and quality.

When I'm running a slide show the pics are only going to be on screen for 4
to 6 seconds. The only reason I keep the files as RAW is so that I can edit
them or print them in high definition while on the other hand I don't want
to have to convert all my pics to jpegs so that I can display them as slide
shows.

Regards

Mych

**Comment by ddurdle** [comment]
promoted to stable
